# Implements: REQ-d00224-A+B+C+D
# Implements: REQ-d00225-A+B
"""Glossary and term index generators for defined terms.

Produces glossary, term index, and collection manifest files in
markdown or JSON format from a TermDictionary.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from elspais.graph.terms import TermDictionary, TermEntry


def _write_readonly(path: Path, content: str) -> None:
    """Write content to path and set it read-only (0o444)."""
    if path.exists():
        path.chmod(0o644)
    path.write_text(content, encoding="utf-8")
    path.chmod(0o444)


_HEADER = (
    "<!-- Auto-generated by: elspais fix -->\n"
    "<!-- Do not edit manually; changes will be overwritten. -->"
)


# Implements: REQ-d00224-A
def generate_glossary(td: TermDictionary, format: str = "markdown") -> str:
    """Generate a glossary from all defined terms.

    Regular terms appear in an alphabetical "Glossary" section.
    Reference-type terms appear in a separate "References" section.

    Args:
        td: The term dictionary to generate from.
        format: "markdown" or "json".

    Returns:
        Formatted glossary content.
    """
    all_entries = sorted(td.iter_all(), key=lambda e: e.term.lower())

    if format == "json":
        data = []
        for entry in all_entries:
            item = {
                "term": entry.term,
                "definition": entry.definition,
                "defined_in": entry.defined_in,
                "namespace": entry.namespace,
                "collection": entry.collection,
                "indexed": entry.indexed,
                "is_reference": entry.is_reference,
                "reference_fields": entry.reference_fields,
                "reference_term": entry.reference_term,
                "reference_source": entry.reference_source,
            }
            data.append(item)
        return json.dumps(data, indent=2)

    # Markdown format — split regular terms from references
    regular = [e for e in all_entries if not e.is_reference]
    references = [e for e in all_entries if e.is_reference]

    # Each entry block ends with one trailing blank line (the `lines.append("")`
    # after every entry); the next letter heading or section follows directly
    # so separators stay at one blank — never two.
    lines = [_HEADER, "# Glossary", ""]
    current_letter = ""

    for entry in regular:
        first_letter = entry.term[0].upper()
        if first_letter != current_letter:
            current_letter = first_letter
            lines.append(f"## {current_letter}")
            lines.append("")

        # Term with annotation
        annotation = ""
        if entry.collection:
            annotation = " *(collection)*"
        elif not entry.indexed:
            annotation = " *(not indexed)*"

        lines.append(f"**{entry.term}**{annotation}")
        lines.append(f": {entry.definition}")
        # Show synonym link if present
        if entry.reference_term:
            source_note = f" ({entry.reference_source})" if entry.reference_source else ""
            lines.append(f"*Reference Term: {entry.reference_term}{source_note}*")
        lines.append(f"*Defined in: {entry.defined_in} ({entry.namespace})*")
        lines.append("")

    # References section
    if references:
        lines.append("# References")
        lines.append("")

        for entry in references:
            lines.append(f"**{entry.term}**")
            rf = entry.reference_fields
            if rf.get("title"):
                lines.append(f": {rf['title']}")
            if rf.get("version"):
                lines.append(f": Version: {rf['version']}")
            if rf.get("effective_date"):
                lines.append(f": Effective Date: {rf['effective_date']}")
            if rf.get("url"):
                lines.append(f": URL: <{rf['url']}>")
            lines.append(f"*Defined in: {entry.defined_in} ({entry.namespace})*")
            lines.append("")

    return "\n".join(lines)


# Implements: REQ-d00224-B
def generate_term_index(
    td: TermDictionary,
    format: str = "markdown",
    ref_filter: Callable[[Any], bool] | None = None,
) -> str:
    """Generate a term index from indexed terms only.

    Args:
        td: The term dictionary to generate from.
        format: "markdown" or "json".
        ref_filter: Optional predicate on a TermReference. When provided,
            references for which it returns False are omitted. Used to keep
            associate-repo references out of the primary term index when
            ``federation.index_associates`` is false (REQ-d00253-C).

    Returns:
        Formatted term index content.
    """
    entries = sorted(td.iter_indexed(), key=lambda e: e.term.lower())

    def _refs(entry):
        if ref_filter is None:
            return entry.references
        return [ref for ref in entry.references if ref_filter(ref)]

    if format == "json":
        data = []
        for entry in entries:
            refs_by_ns: dict[str, list[str]] = defaultdict(list)
            for ref in _refs(entry):
                refs_by_ns[ref.namespace].append(ref.node_id)
            data.append(
                {
                    "term": entry.term,
                    "references": dict(refs_by_ns),
                }
            )
        return json.dumps(data, indent=2)

    # Markdown format. Each major section ends with one trailing blank line
    # (the last per-namespace `lines.append("")`); the next section follows
    # directly to keep separators at one blank — never two.
    lines = [_HEADER, "# Term Index", ""]

    for entry in entries:
        lines.append(f"## {entry.term}")
        lines.append("")

        # Group references by namespace
        refs_by_ns: dict[str, list[str]] = defaultdict(list)
        for ref in _refs(entry):
            if ref.node_id not in refs_by_ns[ref.namespace]:
                refs_by_ns[ref.namespace].append(ref.node_id)

        for ns in sorted(refs_by_ns):
            lines.append(f"**{ns}:**")
            lines.append("")
            for node_id in refs_by_ns[ns]:
                lines.append(f"- {node_id}")
            lines.append("")

    return "\n".join(lines)


# Implements: REQ-d00224-C
def generate_collection_manifest(
    entry: TermEntry,
    format: str = "markdown",
    ref_filter: Callable[[Any], bool] | None = None,
) -> str:
    """Generate a standalone collection manifest for one collection term.

    Args:
        entry: The TermEntry (must have collection=True).
        format: "markdown" or "json".
        ref_filter: Optional predicate on a TermReference; references for
            which it returns False are omitted (REQ-d00253-C).

    Returns:
        Formatted manifest content.
    """
    refs = (
        entry.references if ref_filter is None else [r for r in entry.references if ref_filter(r)]
    )

    if format == "json":
        refs_by_ns: dict[str, list[str]] = defaultdict(list)
        for ref in refs:
            refs_by_ns[ref.namespace].append(ref.node_id)
        data = {
            "term": entry.term,
            "definition": entry.definition,
            "references": dict(refs_by_ns),
        }
        return json.dumps(data, indent=2)

    # Markdown format
    lines = [_HEADER, "", f"# {entry.term}", ""]
    lines.append(f": {entry.definition}")
    lines.append("")

    refs_by_ns: dict[str, list[str]] = defaultdict(list)
    for ref in refs:
        if ref.node_id not in refs_by_ns[ref.namespace]:
            refs_by_ns[ref.namespace].append(ref.node_id)

    for ns in sorted(refs_by_ns):
        lines.append(f"**{ns}:**")
        lines.append("")
        for node_id in refs_by_ns[ns]:
            lines.append(f"- {node_id}")
        lines.append("")

    return "\n".join(lines)


# Implements: REQ-d00225-B
def write_term_outputs(
    td: TermDictionary,
    output_dir: str | Path,
    format: str = "markdown",
    ref_filter: Callable[[Any], bool] | None = None,
) -> list[str]:
    """Write glossary, term index, and collection manifests to output_dir.

    Args:
        ref_filter: Optional predicate on a TermReference applied to the term
            index and collection manifests; references for which it returns
            False are omitted. The glossary lists definitions only and is
            unaffected. Used to keep associate-repo references out of the
            primary artifacts when ``federation.index_associates`` is false
            (REQ-d00253-C).

    Returns:
        List of generated file paths.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []

    ext = ".json" if format == "json" else ".md"

    # Glossary (definitions only — no references to filter)
    glossary_path = out / f"glossary{ext}"
    _write_readonly(glossary_path, generate_glossary(td, format=format))
    generated.append(str(glossary_path))

    # Term index
    index_path = out / f"term-index{ext}"
    _write_readonly(index_path, generate_term_index(td, format=format, ref_filter=ref_filter))
    generated.append(str(index_path))

    # Collection manifests
    collections_dir = out / "collections"
    for entry in td.iter_collections():
        collections_dir.mkdir(parents=True, exist_ok=True)
        slug = entry.term.lower().replace(" ", "-")
        manifest_path = collections_dir / f"{slug}{ext}"
        _write_readonly(
            manifest_path,
            generate_collection_manifest(entry, format=format, ref_filter=ref_filter),
        )
        generated.append(str(manifest_path))

    return generated


# Implements: REQ-d00225-A
def run(args: argparse.Namespace) -> int:
    """Run glossary or term-index CLI command."""
    from elspais.commands import _engine

    def _compute(graph, config, params):  # type: ignore
        td = graph.terms if hasattr(graph, "terms") else None
        if not td:
            # Try root repo graph
            for entry in graph._repos.values():
                if entry.graph and hasattr(entry.graph, "terms"):
                    td = entry.graph.terms
                    break
        if td is None:
            return {"error": "No terms found in graph"}

        fmt = params.get("format", "markdown")

        if params.get("command") == "glossary":
            content = generate_glossary(td, format=fmt)
            print(content)
        else:
            content = generate_term_index(td, format=fmt)
            print(content)

        return {"success": True}

    params: dict[str, str] = {
        "command": getattr(args, "command", "glossary"),
        "format": getattr(args, "format", "markdown"),
    }
    output_dir = getattr(args, "output_dir", None)
    if output_dir:
        params["output_dir"] = output_dir

    _engine.call(
        f"/api/run/{params['command']}",
        params,
        _compute,
        config_path=getattr(args, "config", None),
    )
    return 0
