# Implements: REQ-d00224-A+B+C+D
"""Glossary and term index generators for defined terms.

Produces glossary, term index, and collection manifest files in
markdown or JSON format from a TermDictionary.
"""

from __future__ import annotations

import json
from collections import defaultdict
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from elspais.graph.terms import TermDictionary, TermEntry

_HEADER = (
    "<!-- Auto-generated by: elspais fix -->\n"
    "<!-- Do not edit manually; changes will be overwritten. -->\n"
)


# Implements: REQ-d00224-A
def generate_glossary(td: TermDictionary, format: str = "markdown") -> str:
    """Generate a glossary from all defined terms.

    Args:
        td: The term dictionary to generate from.
        format: "markdown" or "json".

    Returns:
        Formatted glossary content.
    """
    entries = sorted(td.iter_all(), key=lambda e: e.term.lower())

    if format == "json":
        data = []
        for entry in entries:
            item = {
                "term": entry.term,
                "definition": entry.definition,
                "defined_in": entry.defined_in,
                "namespace": entry.namespace,
                "collection": entry.collection,
                "indexed": entry.indexed,
            }
            data.append(item)
        return json.dumps(data, indent=2)

    # Markdown format
    lines = [_HEADER, "# Glossary\n"]
    current_letter = ""

    for entry in entries:
        first_letter = entry.term[0].upper()
        if first_letter != current_letter:
            current_letter = first_letter
            lines.append(f"\n## {current_letter}\n")

        # Term with annotation
        annotation = ""
        if entry.collection:
            annotation = " *(collection)*"
        elif not entry.indexed:
            annotation = " *(not indexed)*"

        lines.append(f"**{entry.term}**{annotation}")
        lines.append(f": {entry.definition}")
        lines.append(f"*Defined in: {entry.defined_in} ({entry.namespace})*\n")

    return "\n".join(lines)


# Implements: REQ-d00224-B
def generate_term_index(td: TermDictionary, format: str = "markdown") -> str:
    """Generate a term index from indexed terms only.

    Args:
        td: The term dictionary to generate from.
        format: "markdown" or "json".

    Returns:
        Formatted term index content.
    """
    entries = sorted(td.iter_indexed(), key=lambda e: e.term.lower())

    if format == "json":
        data = []
        for entry in entries:
            refs_by_ns: dict[str, list[str]] = defaultdict(list)
            for ref in entry.references:
                refs_by_ns[ref.namespace].append(ref.node_id)
            data.append({
                "term": entry.term,
                "references": dict(refs_by_ns),
            })
        return json.dumps(data, indent=2)

    # Markdown format
    lines = [_HEADER, "# Term Index\n"]

    for entry in entries:
        lines.append(f"\n## {entry.term}\n")

        # Group references by namespace
        refs_by_ns: dict[str, list[str]] = defaultdict(list)
        for ref in entry.references:
            if ref.node_id not in refs_by_ns[ref.namespace]:
                refs_by_ns[ref.namespace].append(ref.node_id)

        for ns in sorted(refs_by_ns):
            lines.append(f"**{ns}:**")
            for node_id in refs_by_ns[ns]:
                lines.append(f"- {node_id}")
            lines.append("")

    return "\n".join(lines)


# Implements: REQ-d00224-C
def generate_collection_manifest(entry: TermEntry, format: str = "markdown") -> str:
    """Generate a standalone collection manifest for one collection term.

    Args:
        entry: The TermEntry (must have collection=True).
        format: "markdown" or "json".

    Returns:
        Formatted manifest content.
    """
    if format == "json":
        refs_by_ns: dict[str, list[str]] = defaultdict(list)
        for ref in entry.references:
            refs_by_ns[ref.namespace].append(ref.node_id)
        data = {
            "term": entry.term,
            "definition": entry.definition,
            "references": dict(refs_by_ns),
        }
        return json.dumps(data, indent=2)

    # Markdown format
    lines = [_HEADER, f"# {entry.term}\n"]
    lines.append(f": {entry.definition}\n")

    refs_by_ns: dict[str, list[str]] = defaultdict(list)
    for ref in entry.references:
        if ref.node_id not in refs_by_ns[ref.namespace]:
            refs_by_ns[ref.namespace].append(ref.node_id)

    for ns in sorted(refs_by_ns):
        lines.append(f"**{ns}:**")
        for node_id in refs_by_ns[ns]:
            lines.append(f"- {node_id}")
        lines.append("")

    return "\n".join(lines)
